const coins = [
  { rank: 1, name: "Bitcoin", symbol: "BTC" },
  { rank: 2, name: "Ethereum", symbol: "ETH" },
  { rank: 3, name: "Tether", symbol: "USDT" },
  { rank: 4, name: "BNB", symbol: "BNB" },
  { rank: 5, name: "Solana", symbol: "SOL" },
  { rank: 6, name: "USD Coin", symbol: "USDC" },
  { rank: 7, name: "XRP", symbol: "XRP" },
  { rank: 8, name: "Dogecoin", symbol: "DOGE" },
  { rank: 9, name: "Cardano", symbol: "ADA" },
  { rank: 10, name: "Avalanche", symbol: "AVAX" },
  { rank: 11, name: "TRON", symbol: "TRX" },
  { rank: 12, name: "Chainlink", symbol: "LINK" },
  { rank: 13, name: "Toncoin", symbol: "TON" },
  { rank: 14, name: "Shiba Inu", symbol: "SHIB" },
  { rank: 15, name: "Polkadot", symbol: "DOT" },
  { rank: 16, name: "Wrapped Bitcoin", symbol: "WBTC" },
  { rank: 17, name: "Bitcoin Cash", symbol: "BCH" },
  { rank: 18, name: "NEAR Protocol", symbol: "NEAR" },
  { rank: 19, name: "Uniswap", symbol: "UNI" },
  { rank: 20, name: "Litecoin", symbol: "LTC" },
  { rank: 21, name: "Dai", symbol: "DAI" },
  { rank: 22, name: "Internet Computer", symbol: "ICP" },
  { rank: 23, name: "LEO Token", symbol: "LEO" },
  { rank: 24, name: "Aptos", symbol: "APT" },
  { rank: 25, name: "Ethereum Classic", symbol: "ETC" },
  { rank: 26, name: "Stellar", symbol: "XLM" },
  { rank: 27, name: "Cosmos", symbol: "ATOM" },
  { rank: 28, name: "Filecoin", symbol: "FIL" },
  { rank: 29, name: "Cronos", symbol: "CRO" },
  { rank: 30, name: "Hedera", symbol: "HBAR" },
  { rank: 31, name: "Arbitrum", symbol: "ARB" },
  { rank: 32, name: "VeChain", symbol: "VET" },
  { rank: 33, name: "Optimism", symbol: "OP" },
  { rank: 34, name: "Injective", symbol: "INJ" },
  { rank: 35, name: "Immutable", symbol: "IMX" },
  { rank: 36, name: "Render", symbol: "RENDER" },
  { rank: 37, name: "The Graph", symbol: "GRT" },
  { rank: 38, name: "Aave", symbol: "AAVE" },
  { rank: 39, name: "Bittensor", symbol: "TAO" },
  { rank: 40, name: "Theta Network", symbol: "THETA" },
  { rank: 41, name: "Algorand", symbol: "ALGO" },
  { rank: 42, name: "Mantle", symbol: "MNT" },
  { rank: 43, name: "Flow", symbol: "FLOW" },
  { rank: 44, name: "Maker", symbol: "MKR" },
  { rank: 45, name: "The Sandbox", symbol: "SAND" },
  { rank: 46, name: "Tezos", symbol: "XTZ" },
  { rank: 47, name: "Decentraland", symbol: "MANA" },
  { rank: 48, name: "EOS", symbol: "EOS" },
  { rank: 49, name: "Axie Infinity", symbol: "AXS" },
  { rank: 50, name: "The Graph", symbol: "GRT" },
  { rank: 51, name: "Quant", symbol: "QNT" },
  { rank: 52, name: "Pyth Network", symbol: "PYTH" },
  { rank: 53, name: "Synthetix", symbol: "SNX" },
  { rank: 54, name: "Fantom", symbol: "FTM" },
  { rank: 55, name: "Gala", symbol: "GALA" },
  { rank: 56, name: "KuCoin Token", symbol: "KCS" },
  { rank: 57, name: "The Sandbox", symbol: "SAND" },
  { rank: 58, name: "dYdX", symbol: "DYDX" },
  { rank: 59, name: "Chiliz", symbol: "CHZ" },
  { rank: 60, name: "JasmyCoin", symbol: "JASMY" },
  { rank: 61, name: "PancakeSwap", symbol: "CAKE" },
  { rank: 62, name: "Lido DAO", symbol: "LDO" },
  { rank: 63, name: "Neo", symbol: "NEO" },
  { rank: 64, name: "IOTA", symbol: "IOTA" },
  { rank: 65, name: "Stacks", symbol: "STX" },
  { rank: 66, name: "Kava", symbol: "KAVA" },
  { rank: 67, name: "Arweave", symbol: "AR" },
  { rank: 68, name: "Axelar", symbol: "AXL" },
  { rank: 69, name: "Curve DAO Token", symbol: "CRV" },
  { rank: 70, name: "FLOKI", symbol: "FLOKI" },
  { rank: 71, name: "Conflux", symbol: "CFX" },
  { rank: 72, name: "Mina", symbol: "MINA" },
  { rank: 73, name: "Oasis", symbol: "ROSE" },
  { rank: 74, name: "Sui", symbol: "SUI" },
  { rank: 75, name: "Celestia", symbol: "TIA" },
  { rank: 76, name: "Sei", symbol: "SEI" },
  { rank: 77, name: "Kaspa", symbol: "KAS" },
  { rank: 78, name: "Bonk", symbol: "BONK" },
  { rank: 79, name: "Jupiter", symbol: "JUP" },
  { rank: 80, name: "Ondo", symbol: "ONDO" },
  { rank: 81, name: "Wormhole", symbol: "W" },
  { rank: 82, name: "Starknet", symbol: "STRK" },
  { rank: 83, name: "Worldcoin", symbol: "WLD" },
  { rank: 84, name: "Immutable", symbol: "IMX" },
  { rank: 85, name: "Blur", symbol: "BLUR" },
  { rank: 86, name: "ApeCoin", symbol: "APE" },
  { rank: 87, name: "Gnosis", symbol: "GNO" },
  { rank: 88, name: "Raydium", symbol: "RAY" },
  { rank: 89, name: "dYdX", symbol: "DYDX" },
  { rank: 90, name: "Notcoin", symbol: "NOT" },
  { rank: 91, name: "Jito", symbol: "JTO" },
  { rank: 92, name: "Pendle", symbol: "PENDLE" },
  { rank: 93, name: "Beam", symbol: "BEAM" },
  { rank: 94, name: "Akash Network", symbol: "AKT" },
  { rank: 95, name: "Flare", symbol: "FLR" },
  { rank: 96, name: "LayerZero", symbol: "ZRO" },
  { rank: 97, name: "Ethena", symbol: "ENA" },
  { rank: 98, name: "Aerodrome", symbol: "AERO" },
  { rank: 99, name: "Starknet", symbol: "STRK" },
  { rank: 100, name: "Jupiter", symbol: "JUP" }
];

module.exports = coins;